### ISSUE TITLE
Исправьте генерацию оплаты

### ISSUE THREAD

**Issue by gayanov** [unitpay/php-sdk#11]
Когда подключал вашу систему, не мог получить параметры desc, sum, из-за того что в коде Unitpay.php, была обнаружена ошибка последовательности, то есть,
до изменения:
```
        $vitalParams = array(
            'account'  => $account,
            'currency' => $currency,
            'desc'     => $desc,
            'sum'      => $sum
        );
        $this->params = array_merge($this->params, $vitalParams);
 
        if ($this->secretKey) {
            $this->params['signature'] = $this->getSignature($vitalParams);
        }

        $this->params['locale'] = $locale;
```
после изменений:
```
       $vitalParams = array(
            'account'  => $account,
            'currency' => $currency,
            'desc'     => $desc,
            'sum'      => $sum
        );
 
        if ($this->secretKey) {
            $this->params['signature'] = $this->getSignature($vitalParams);
        }
 
        $this->params = array_merge($this->params, $vitalParams);
 
        $this->params['locale'] = $locale;

```
То есть поменял местами. Надеюсь исправите)

**Comment by m16a1** [comment]
По всей видимости вы решаете проблему того, что `$this->params` не инициализирован, из-за чего `array_merge` возвращает `null`, поскольку первый аргумент равен `null`. Однако, обращаю ваше внимание, что это решение будет работать, только в случае, если используется secretKey.

Для решения этой проблемы было предложено другое решение — https://github.com/unitpay/php-sdk/pull/10, которое влито в master.

**Comment by gayanov** [comment]
secretKey был передан.
