### ISSUE TITLE
Wrong signature

### ISSUE THREAD

**Issue by megaezz** [unitpay/php-sdk#20]
Обновился на версию 2.0.3 - стали сыпаться ошибки Wrong signature.
Откатился на 2.0.2 - все ок.

**Comment by 2Garin** [comment]
Добрый день.
Пришлите подробности на a.ostroverkhov@unitpay.ru: id проекта и ориентировочное время, когда вы выполняли запросы.
В идеале сам ошибочный запрос.

**Comment by megaezz** [comment]
Проект 163001 17 марта 01:22 - 02:30

**Comment by megaezz** [comment]
отправил

**Comment by 2Garin** [comment]
@megaezz проблему исправили в версии 2.0.4, проверьте
