### ISSUE TITLE
Баги и улучшения

### ISSUE THREAD

**Issue by mikedin** [unitpay/php-sdk#22]
1. Домен, который
$unitpay = new UnitPay($domain, $secretKey);
вообще стоит назвать api domain или еще как, но только не Your domain, потому, что для клиентов your domain это их домен, домен магазина и никак не домен, к которому идут запросы на api unitpay

2. Бага
Уж не знаю где, но судя по всему на сервере помимо params['signature'] где-то вписывается еще и params['sign']
Наверно достаточно давно уже.
Как вы думаете, работает ли проверка сигнатуры с текущим описанным в документации алгоритмом? Нет, очевидно не работает.
Зато где-то в соседнем проекте было найдено
    public function getSignature(array $params, $method = null)
    {
+        unset($params['sign']); // вот эта строчка, добавление которой внезапно чинит проверку
        unset($params['signature']);

3. Ключик который secretKey оказывается не один, их три. проекта, api и тестовый api.
внезапно, они оказываются одинаковыми в плане имени переменной и надо просто вот тут
$unitpay = new UnitPay($domain, $secretKey);
во втором параметре их подбирать по одному, чтобы понять где (в смысле при создании платежа или проверке) и какой (из трех) ставить
оказалось, их надо ставить в одном месте один, в другом - другой. 6 вариантов, их всего лишь перебрать...

Это все бы починить. И в документации тоже, но
п2. Критичный, как наверно видно, те хотелось бы его в первую очередь поправить и влить, чтобы работало без костылей.

**Comment by unitpayService** [comment]
Добрый день!
Большое спасибо за ваши предложения, мы внесли правки в файл README.md.

Напишите пожалуйста на почту partners@unitpay.ru со своей регистрационной почты по проблеме с сигнатурой.

**Comment by mikedin** [comment]
Добрый день
$domain = 'unitpay.ru'; // Your working domain
все еще остался. или решили его не менять?

**Comment by unitpayService** [comment]
Добрый день!
Большое спасибо за вашу бдительность, мы внесли правки в файл README.md.

**Comment by mikedin** [comment]
Да, спасибо! п.1 закрыли.
А вот п.3
$secretKey  = '9e977d0c0e1bc8f5cc9775a8cc8744f1';// Project secret key
Это не везде вроде так? для хендлера платежа - да, при Init payment - нужен ключ вроде не проекта же, а api?
