### ISSUE TITLE
file_get_contents

### ISSUE THREAD

**Issue by malsatin** [unitpay/php-sdk#7]
Есть мнение, что делать запросы по https через функцию file_get_contents - это не лучшая идея. Предлагаю вместо этого использовать что-то вроде
```
	public function httpGetContents($url) {
		$curl = curl_init();

		curl_setopt($curl, CURLOPT_URL, $url);
		curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

		$result = curl_exec($curl);
		curl_close($curl);

		return $result;
	}
```

**Comment by AlexGx** [comment]
Спасибо за предложение по улучшению, мы реализуем это в следующем большом релизе
