### ISSUE TITLE
api method

### ISSUE THREAD

**Issue by malsatin** [unitpay/php-sdk#8]
Предлагаю в функцию UnitPay::api добавить автоматическое добавление параметра ip пользователя

**Comment by RomaZveR25** [comment]
Это поломает очень много интеграций. бекенд может стоять за прокси (nginx, haproxy итд) или сервисами аля cloudflare, где нужно либо править конфиги веб сервера, либо дергать ip посетителя из специальной переменной, например `$_SERVER["HTTP_CF_CONNECTING_IP"]`.

**Comment by MattRh** [comment]
С чего это должно поломать, если уже есть метод `UnitPay::getIp()`. Я лишь предлагаю на эту строку https://github.com/unitpay/php-sdk/blob/master/UnitPay.php#L256 добавить этот код 
```php
$params['ip'] = $this->getIp();
```

И за одно можно перенести эту строку https://github.com/unitpay/php-sdk/blob/master/UnitPay.php#L285 сюда https://github.com/unitpay/php-sdk/blob/master/UnitPay.php#L307-L308

**Comment by RomaZveR25** [comment]
Метод `UnitPay::getIp()` protected, его можно переопределить под свои нужды если источник ip адреса нестандартный.
Энивей, правда ваша. Набросал в своем форке, можете протестировать если есть желание и возможность, там, кстати допилена полная поддержка всех методов api. 
[https://github.com/RomaZveR25/php-sdk](url)

**Comment by AlexGx** [comment]
> Метод `UnitPay::getIp()` protected, его можно переопределить под свои нужды если источник ip адреса нестандартный.
> Энивей, правда ваша. Набросал в своем форке, можете протестировать если есть желание и возможность, там, кстати допилена полная поддержка всех методов api и CURL вместо file_get_contents.
> [https://github.com/RomaZveR25/php-sdk]

Спасибо за предложения по улучшениям!
